// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4959.StaleyRobotics2015.subsystems;

import org.usfirst.frc4959.StaleyRobotics2015.RobotMap;
import org.usfirst.frc4959.StaleyRobotics2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drivetrain extends Subsystem {

    SpeedController speedController1 = RobotMap.leftTalon;
    SpeedController speedController2 = RobotMap.rightTalon;
    SpeedController speedController3 = RobotMap.backTalon;
    SpeedController speedController4 = RobotMap.frontTalon;
    
    RobotDrive robotDrive = RobotMap.drivetrainRobotDrive;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {

        setDefaultCommand(new DriveWithJoysticks());
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
//    public void getJoystickInputs(Joystick left, Joystick right) {
//    	robotDrive.tankDrive(left, right);
//    }
    
    public void arcadeDrive(double forward, double sideways) {
    	if (forward > 0 && forward < 0) {
    		robotDrive.arcadeDrive(forward, sideways = 0);
    	}
    	if (sideways > 0 && sideways <0) {
    		robotDrive.arcadeDrive(forward = 0, sideways);
    	} 
    }

	public void stop() {
		robotDrive.drive(0, 0);
	}
}

